# Why this file is written:
# This file defines the Pydantic validation schemas for the AI Chatbot endpoints.
# It handles input validation for incoming chat requests (like user queries and session IDs)
# and formats responses returned by the AI engine, ensuring clean data exchanges.

from pydantic import BaseModel, Field, ConfigDict
from typing import Optional
from datetime import datetime

# ----------------------------------------------------
# Request Schemas (API Inputs)
# ----------------------------------------------------
class ChatRequest(BaseModel):
    """
    Validation schema for an incoming chat query.
    
    Attributes:
        session_id (str): A unique token representing the current chat session, used for memory retrieval.
        message (str): The raw text query submitted by the student.
    """
    session_id: str = Field(..., description="Unique ID for the conversation session (to maintain message history)")
    message: str = Field(..., min_length=1, description="The message text query to send to the chatbot")

# ----------------------------------------------------
# Response Schemas (API Outputs)
# ----------------------------------------------------
class ChatResponse(BaseModel):
    """
    Validation schema for returning the AI response back to the client.
    
    Attributes:
        session_id (str): The session ID of the conversation.
        response (str): The text response generated by the AI model.
    """
    session_id: str = Field(..., description="The session ID associated with the reply")
    response: str = Field(..., description="The generated response text from the AI assistant")

class ChatHistoryResponse(BaseModel):
    """
    Validation schema for returning past conversation logs.
    
    Attributes:
        id (int): Database record key.
        session_id (str): The session ID.
        user_message (str): What the user said.
        ai_response (str): What the AI replied.
        created_at (datetime): When the conversation occurred.
    """
    id: int
    session_id: str
    user_message: str
    ai_response: str
    created_at: datetime

    # ConfigDict allows Pydantic V2 to serialize directly from SQLAlchemy models
    model_config = ConfigDict(from_attributes=True)
